steps:
  - name: ":rspec:"
    commands: 
      - bundle install
      - bundle exec rspec

  - name: "rubocop :male-police-officer:"
    commands: 
      - bundle install
      - bundle exec rubocop
  
  - block: ":rubygems: Publish :red_button:"
    if: build.tag != null
  
  - name: "Push :rubygems:"
    commands: "./bin/publish"
    if: build.tag != null
