steps:
  - name: ":rspec:"
    commands: 
      - bundle install
      - bundle exec rspec

  - name: "rubocop :male-police-officer:"
    commands: 
      - bundle install
      - bundle exec rubocop
  
  - block: ":rubygems: Publish :red_button:"
    branches: "main"
  
  - name: "Push :rubygems:"
    commands: "./bin/publish"
    branches: "main"