name: auto-merge

on:
  pull_request:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.TOKEN }}
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.TOKEN }}"
      
